name: SB CI/CD with Gradle

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set prod.yml
        run: |
          cd ./src/main/resources
          sed -i 's|${DB_URL}|'"${{ secrets.DB_URL }}"'|g' application-prod.yml
          sed -i 's|${DB_USER}|'"${{ secrets.DB_USER }}"'|g' application-prod.yml
          sed -i 's|${DB_PASSWORD}|'"${{ secrets.DB_PASSWORD }}"'|g' application-prod.yml

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --platform linux/amd64 -t wendyjihyo77/sookbackend .
          docker push wendyjihyo77/sookbackend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_NAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo usermod -aG docker $USER

            # 8080 포트 사용 중이면 종료
            if sudo lsof -i :8080; then
              echo "Port 8080 is in use. Stopping the process..."
              sudo fuser -k 8080/tcp
            fi

            # 기존 컨테이너 삭제 (이미 존재하면 강제 삭제)
            if [ "$(sudo docker ps -a -q -f name=sookserver)" ]; then
              echo "Stopping and removing existing sookserver container..."
              sudo docker stop sookserver || true
              sudo docker rm sookserver || true
            fi

            # 기존 이미지 삭제
            sudo docker image rm -f wendyjihyo77/sookbackend || true

            # 새로운 이미지 풀링
            sudo docker pull wendyjihyo77/sookbackend

            # 새 컨테이너 실행
            sudo docker run -d \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e EC2_HOST=${{ secrets.EC2_HOST }} \
              --name sookserver -p 8080:8080 wendyjihyo77/sookbackend
